config/routes.rb
Pinger::Application.routes.draw do
  root to: "locations#index"

  resources :locations do
    member do
      get :delete
    end

    resources :alerts
  end

  resources :email_callbacks do
    member do
      get :delete
    end
  end

  resources :alerts

  namespace 'admin' do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/email_callback.rb
class EmailCallback < ActiveRecord::Base

  validates :to, :presence => true, :length => {:maximum => 255}
  validates :label, :presence => true, :uniqueness => true, :length => {:maximum => 255}

  def to_s
    label.to_s
  end

end

app/controllers/email_callbacks_controller.rb
class EmailCallbacksController < ApplicationController
  respond_to :html

  helper_method :email_callback

  def create
    email_callback.save
    respond_with email_callback, location: email_callbacks_url
  end

  def update
    email_callback.attributes = params[:email_callback]
    email_callback.save
    respond_with email_callback, location: email_callbacks_url
  end

  def destroy
    email_callback.destroy
    respond_with email_callback
  end

  # TODO: test
  def email_callback
    @email_callback ||= begin
      if params[:id]
        EmailCallback.find params[:id]
      else
        EmailCallback.new params[:email_callback]
      end
    end
  end
end

app/views/email_callbacks/_form.html.haml
= form_for email_callback do |f|
  = render 'shared/form_errors', :errors => email_callback.errors.full_messages

  .label.input
    %div= f.label :label
    %div= f.text_field :label, max_length: 255, size: 50

  .email.input
    %div= f.label :to, 'Email'
    %div= f.text_field :to, max_length: 255, size: 50

  %p
    %button
      = email_callback.new_record? ? 'Add' : 'Save'
      email callback

app/views/email_callbacks/_table.html.haml
%table
  %thead
    %tr
      %th Label
      %th Email
      %th
  %tbody
    - email_callbacks.each do |email_callback|
      - email_callback = present email_callback
      %tr{id: "email_callback_#{email_callback.id}"}
        %td= email_callback.label
        %td= email_callback.to
        %td
          %ul
            %li.edit
              = link_to email_callback.edit_path, title: 'Edit this email callback' do
                %span edit
            %li.remove
              = link_to email_callback.delete_path, title: 'Remove this email callback' do
                %span remove

app/views/email_callbacks/delete.html.haml
%h2 Remove email callback

= form_tag email_callback_path(email_callback), :method => :delete do
  %p
    Are you sure you want to
    %strong Remove this email callback?
  = button_tag 'Yes, remove it'
  = link_to 'cancel', root_path

app/views/email_callbacks/edit.html.haml
%p= link_to 'Back', root_path

%h2 Edit Email Callback

= render 'form', email_callback: email_callback

app/views/email_callbacks/index.html.haml
#email_callbacks
  %h2 Email callbacks

  %p= link_to 'Add email callback', new_email_callback_path

  - if email_callbacks.present?
    = render 'email_callbacks/table', :email_callbacks => email_callbacks
  - else
    %p.empty No email callbacks found.

app/views/email_callbacks/new.html.haml
%p= link_to 'Back', root_path

%h2 Add Email Callback

= render 'form', email_callback: email_callback