config/routes.rb
Pinger::Application.routes.draw do
  root to: "locations#index"

  resources :locations do
    member do
      get :delete
    end

    resources :alerts
  end

  resources :email_callbacks do
    member do
      get :delete
    end
  end

  resources :alerts

  namespace 'admin' do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  HTTP_METHODS = %w[GET POST]

  class << self
    def find_by_param(param)
      find_by_id param
    end

    def without_scheduled_ping
      all.reject &:scheduled_ping
    end
  end

  validates :seconds, :presence => true, :numericality => {:if => lambda { seconds.present? }}
  validates :http_method, :inclusion => HTTP_METHODS
  validates :url,
    :presence => true,
    :format => {:with => /\A#{URI.regexp %w(http https)}\z/, :if => lambda { url.present? }}
  validates :title, :presence => true

  # has_many :alerts
  has_many :pings

  def next_ping_time
    (performed_pings.first.try(:performed_at) || created_at) + seconds
  end

  def schedule_ping!
    PingWorker.perform_at(next_ping_time, pings.create!.id)
  end

  def scheduled_ping
    pings.where(:performed_at => nil).first
  end

  def paginated_performed_pings(page: 1, per_page: CONFIG[:app][:pings_per_page])
    performed_pings.page(page).per(per_page)
  end

  private

  def performed_pings
    pings.where('performed_at IS NOT NULL').order('performed_at DESC')
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  respond_to :html

  before_filter :assign_location, :only => [:show, :edit, :update, :delete, :destroy]
  before_filter :assign_new_location, :only => [:new, :create]

  attr_reader :locations, :location, :paginated_pings

  helper_method :locations, :location, :paginated_pings

  def index
    @locations = user.paginated_locations_ordered_by_title(:page => params[:page])
  end

  def show
    @paginated_pings = @location.paginated_performed_pings(:page => params[:page])
  end

  def create
    if @location.save
      redirect_to location_url(@location)
    else
      render :new
    end
  end

  def update
    @location.attributes = params[:location]
    if @location.save
      redirect_to location_url(@location)
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to locations_url
  end

  private

  def assign_location
    @location = user.find_location_by_param(params[:id]) or render_not_found
  end

  def assign_new_location
    @location = user.new_location params[:location]
  end
end

app/views/locations/_form.html.haml
= form_for location, :role => 'form' do |f|
  .form-group
    = f.label :title
    = f.text_field :title, :max_length => 255, :size => 50, :class => 'form-control'
    - if (errors = location.errors[:title]).present?
      = render 'shared/form_errors', :errors => errors.map(&:capitalize)

  .form-group
    = f.label :url, 'URL'
    = f.text_field :url, :max_length => 255, :size => 80, :class => 'form-control'
    - if (errors = location.errors[:url]).present?
      = render 'shared/form_errors', :errors => errors.map(&:capitalize)

  .form-group
    = f.label :http_method, 'HTTP method'
    = f.select :http_method, Location::HTTP_METHODS.map(&:upcase), {}, :class => 'form-control'
    - if (errors = location.errors[:http_method]).present?
      = render 'shared/form_errors', :errors => errors.map(&:capitalize)

  .form-group
    = f.label :seconds
    = f.text_field :seconds, :max_length => 255, :size => 20, :class => 'form-control'
    - if (errors = location.errors[:seconds]).present?
      = render 'shared/form_errors', :errors => errors.map(&:capitalize)

  = f.button "#{location.persisted? ? 'Save' : 'Add'} URL", :class => 'btn btn-default'

app/views/locations/delete.html.haml
%h2 Remove URL

= form_tag location_path(location), :method => :delete do
  %p
    Are you sure you want to
    %strong Remove this URL?

  = button_tag 'Yes, remove it', :class => 'btn btn-default'
  = link_to 'cancel', root_path

app/views/locations/index.html.haml
#locations
  %h2 URLs

  %p
    = link_to "Add URL", new_location_path
    |
    = link_to "Email callbacks", email_callbacks_path
    |
    = link_to "Alerts", alerts_path

  - if locations.present?
    %table.table
      %thead
        %tr
          %th Title
          %th URL
          %th HTTP method
          %th Seconds
          %th
        %tbody
          - locations.each do |location|
            %tr{id: "url_#{location.id}"}
              %td= link_to location.title, location_path(location)
              %td= location.url
              %td= location.http_method.upcase
              %td= location.seconds
              %td
                = link_to 'edit', edit_location_path(location), title: 'Edit this URL'
                |
                = link_to 'remove', delete_location_path(location), title: 'Remove this URL'
  - else
    %p.empty No URLs found.

  = paginate locations

app/views/locations/show.html.haml
%p
  = link_to 'Back', root_path
  |
  = link_to 'Add alert', new_location_alert_path(location)

#location
  #info
    %table
      %tbody
        %tr
          %th Title
          %td= location.title
        %tr
          %th URL
          %td= location.url
        %tr
          %th HTTP method
          %td= location.http_method.upcase
        %tr
          %th Seconds
          %td= location.seconds
    #pings
      %h2 Pings
      %p
        Next ping in
        - if location.next_ping_time && location.next_ping_time > (now = Time.now)
          #{distance_of_time_in_words now, location.next_ping_time}.
        - else
          just a moment.

      - if paginated_pings.present?
        = render 'pings/table', pings: paginated_pings
      - else
        %p.empty No pings yet.

      = paginate paginated_pings